version: '3.0'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - some-net
    depends_on:
      - db
    restart: on-failure
  db:
    container_name: postgress-db
    image: postgres
    environment:
     PG_DATA: var/lib/postgresql/data
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - some-net
    restart: on-failure
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - some-net
networks:
   some-net:
    driver: bridge
volumes:
  pgdata:
