version: '3.0'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db
    restart: always
  db:
    container_name: postgress-db
    image: postgres
    environment:
     PG_DATA: var/lib/postgresql/data
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always


